name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_test:
    uses: ./.github/workflows/test.yml
    with:
      ufbx-documentation-ref: ${{ github.ref }}
      ufbx-rust-ref: main
