name: Test

on:
  workflow_call:
    inputs:
      ufbx-documentation-ref:
        required: true
        type: string
      ufbx-rust-ref:
        required: true
        type: string
      ufbx-ref:
        required: false
        type: string

jobs:

  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ufbx/ufbx.github.io
          ref: ${{ inputs.ufbx-documentation-ref }}
          fetch-depth: 2
      - name: Update ufbx
        if: inputs.ufbx-ref
        run: python3 sfs.py --verbose update ufbx=${{ inputs.ufbx-ref }} --overwrite

      - name: Install PyPI dependencies
        run: pip install -r tests/requirements.txt
      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Download SHDC
        run: |
          curl https://raw.githubusercontent.com/floooh/sokol-tools-bin/33d2e4cc26088c6c28eaef5467990f8940d15aab/bin/linux/sokol-shdc -o sokol-shdc
          chmod +x sokol-shdc
          pwd >> $GITHUB_PATH
      - name: Build native
        run: |
          cd native
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          cmake --build build
      - name: Build scripts
        run: |
          cd script
          npm install
          npm run build
      - name: Build site
        run: |
          npm install
          npm run build
      - name: Lint HTML
        run: python3 tests/lint-html.py

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ufbx/ufbx.github.io
          ref: ${{ inputs.ufbx-documentation-ref }}
          fetch-depth: 2
      - name: Update ufbx
        if: inputs.ufbx-ref
        run: python3 sfs.py --verbose update ufbx=${{ inputs.ufbx-ref }} --overwrite

      - uses: ufbx/ufbx-rust/.github/workflows/build.yml@${{ inputs.ufbx-rust-ref }}
        with:
          ufbx-rust-ref: ${{ inputs.ufbx-rust-ref }}
          ufbx-ref: ${{ inputs.ufbx-ref }}

      - name: Compile examples
        run: python3 tests/compile-examples.py --ufbx-rust-path ../ufbx-rust
